# R2Devops.io pipeline generation
#
# List of technologies detected in the project : c&#43;&#43;, gradle, html, java Properties, json, kotlin, markdown, perl, swift, yaml, 

name: R2Devops
on:
  push:
    branches: [ master, r2devops]
  pull_request:
    branches: [ master ]

jobs:
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Run the Gradle package task
        uses: gradle/gradle-build-action@0d13054264b0bb894ded474f08ebb30921341cee
        with:
          arguments: build

  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: gitleaks-action
      uses: zricethezav/gitleaks-action@master




# R2devops.io customization
# You can update them in your project dashboard

สวัสดี
8000
6666
8888
4444